'use strict';
/**
 * Structure-discovery report — plain-English write-up of the unsupervised
 * content clustering (src/discover_structure.js). Reads the discovery JSON +
 * cluster summary and emits reports/structure_discovery_report.md (GitHub-renderable).
 */
const fs = require('fs');
const path = require('path');
const { ROOT, loadConfig } = require('./config');

const cfg = loadConfig();
const J = JSON.parse(fs.readFileSync(path.join(ROOT,'data/processed/structure_discovery.json'),'utf8'));
const clusters = J.clusters.slice().sort((a,b)=>b.avg_engagement-a.avg_engagement);
const top = clusters[0], bottom = clusters[clusters.length-1];
const ratio = bottom.avg_engagement>0 ? Math.round(top.avg_engagement/bottom.avg_engagement) : null;
const sep = J.silhouette < 0.1 ? 'weak (themes overlap heavily; treat clusters as soft, indicative groupings rather than hard segments)'
          : J.silhouette < 0.25 ? 'moderate' : 'clear';

const rows = clusters.map((c,i)=>`| ${i+1} | ${c.size} (${c.share_pct}%) | **${c.avg_engagement.toLocaleString()}** | ${c.top_terms} |`).join('\n');

const md = `# ${cfg.client.name}: Data-Driven Content Structure
*Unsupervised discovery · ${J.n_docs} posts · seed ${J.seed} · fully reproducible*

---

## What this is

Instead of sorting posts into categories we chose in advance, this analysis lets the **data choose the categories**. Every post's caption, hashtags and mentions are turned into a numeric "fingerprint" (TF-IDF), and an unsupervised algorithm (**k-means clustering**, with the number of groups chosen automatically by silhouette score) groups posts that use similar language. A PCA projection then places every post on a 2-D map so similar posts sit close together.

This is interpretable machine learning, chosen deliberately over a black-box neural network: at this data scale it is **reproducible** (fixed seed → identical result every run) and every grouping can be inspected and explained. It is exploratory: it surfaces hypotheses about how the content naturally organises, which the keyword pillars in the main report cannot.

> **Method honesty.** The clusters were selected at k=${J.chosen_k} with a mean silhouette of **${J.silhouette}**, i.e. separation is ${sep}. The value here is not crisp segmentation but the **engagement pattern across themes** below, which is clear and actionable.

![Content map of discovered themes](figures/clusters_pca.svg)

---

## The themes the data revealed

Ordered by average engagement (highest first):

| Theme | Posts | Avg engagement | Defining words (auto-extracted) |
|---|---|---:|---|
${rows}

---

## What stands out

- **Top theme, "${top.top_terms.split(', ').slice(0,3).join(', ')}", averages ${top.avg_engagement.toLocaleString()} engagement${ratio?`, about ${ratio}x the lowest theme ("${bottom.top_terms.split(', ').slice(0,3).join(', ')}", ${bottom.avg_engagement.toLocaleString()})`:''}.** The data is pointing clearly at which kind of content the audience rewards.
- The keyword classifier in the main report put roughly nine in ten posts into a single bucket; this unsupervised view **separates that bucket into distinct content franchises** the account actually runs, each with very different engagement.
- The biggest opportunity is usually a theme that is **high-engagement but low-volume**: it works, but is under-produced. Compare each theme's share of posts against its average engagement in the table above.

## How to use this

1. Treat the top one or two themes as **proven formats**: produce more of them.
2. For a high-engagement but small-share theme, test increasing its frequency and watch whether the average holds.
3. For a high-volume but low-engagement theme, ask whether it is worth the effort, or whether it can be reframed using the language of the winning themes.
4. Re-run this analysis each quarter; because the seed is fixed, any change in the map reflects a real change in the content, not randomness.

*Generated by \`src/discover_structure.js\` + \`src/generate_structure_report.js\`, pure Node, no external dependencies, seed ${J.seed}.*
`;

fs.writeFileSync(path.join(ROOT,'reports','structure_discovery_report.md'), md);
console.log('✓ reports/structure_discovery_report.md written');
